// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badexample1: typeof import('./examples/badexample1.md')['default']
    Badexample2: typeof import('./examples/badexample2.md')['default']
    Closedtypeex: typeof import('./examples/closedtypeex.md')['default']
    Depthtypex: typeof import('./examples/depthtypex.md')['default']
    Example: typeof import('./components/example.vue')['default']
    Immutableobjects: typeof import('./examples/immutableobjects.md')['default']
    Listexample: typeof import('./examples/listexample.md')['default']
    Objectexample: typeof import('./examples/objectexample.md')['default']
    Objpolyexample: typeof import('./examples/objpolyexample.md')['default']
    Proargpoly: typeof import('./examples/proargpoly.md')['default']
    Refexample: typeof import('./examples/refexample.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/slide.vue')['default']
    Slide2sides: typeof import('./components/slide2sides.vue')['default']
    Subtypingbad: typeof import('./examples/subtypingbad.md')['default']
    Subtypinggood: typeof import('./examples/subtypinggood.md')['default']
    Variance: typeof import('./examples/variance.md')['default']
    Variance2: typeof import('./examples/variance2.md')['default']
    Variantsubtyping: typeof import('./examples/variantsubtyping.md')['default']
    Widthsubtyping: typeof import('./examples/widthsubtyping.md')['default']
  }
}

export {}
